vars: {
  d2-config: {
    sketch: true
  }
}
classes: {
  file: {
    label: ""
    shape: diamond
    style: {
      fill: yellow
      shadow: true
    }
  }
}

classes: {
  class: {
    label: ""
    shape: hexagon
    style: {
      fill: lightblue
      shadow: true
    }
  }
}

classes: {
  function: {
    label: ""
    shape: rectangle
    style: {
      fill: white
      shadow: false
    }
  }
}
download_weights.main.class: function
download_weights.main.label: "main"
download_weights.main: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
download_weights.reverse_permute.class: function
download_weights.reverse_permute.label: "reverse_permute"
download_weights.reverse_permute: {
  style: {
    opacity: 0.60
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
download_weights.download_weights.class: file
download_weights.download_weights.label: "download_weights"
download_weights.download_weights: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
download_weights.fixed_get_imports.class: function
download_weights.fixed_get_imports.label: "fixed_get_imports"
download_weights.fixed_get_imports: {
  style: {
    opacity: 0.60
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
download_weights.translate_key.class: function
download_weights.translate_key.label: "translate_key"
download_weights.translate_key: {
  style: {
    opacity: 0.60
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
download_weights.main -> download_weights.reverse_permute: {
  style.stroke: black
  style.opacity: 0.60
  style.stroke-width: 2
}
download_weights.main -> download_weights.translate_key: {
  style.stroke: black
  style.opacity: 0.60
  style.stroke-width: 2
}
download_weights.download_weights -> download_weights.fixed_get_imports: {
  style.stroke: red
  style.opacity: 0.60
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> download_weights.reverse_permute: {
  style.stroke: red
  style.opacity: 0.60
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> download_weights.main: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> download_weights.translate_key: {
  style.stroke: red
  style.opacity: 0.60
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}