vars: {
  d2-config: {
    sketch: true
  }
}
classes: {
  file: {
    label: ""
    shape: diamond
    style: {
      fill: yellow
      shadow: true
    }
  }
}

classes: {
  class: {
    label: ""
    shape: hexagon
    style: {
      fill: lightblue
      shadow: true
    }
  }
}

classes: {
  function: {
    label: ""
    shape: rectangle
    style: {
      fill: white
      shadow: false
    }
  }
}
download_weights.download_weights.class: file
download_weights.download_weights.label: "download_weights"
download_weights.download_weights: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_kvcache.torch_kvcache.class: file
entropix.torch_kvcache.torch_kvcache.label: "torch_kvcache"
entropix.torch_kvcache.torch_kvcache: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.config.config.class: file
entropix.config.config.label: "config"
entropix.config.config: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.prompts.prompts.class: file
entropix.prompts.prompts.label: "prompts"
entropix.prompts.prompts: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.kvcache.kvcache.class: file
entropix.kvcache.kvcache.label: "kvcache"
entropix.kvcache.kvcache: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.model.model.class: file
entropix.model.model.label: "model"
entropix.model.model: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.tokenizer.tokenizer.class: file
entropix.tokenizer.tokenizer.label: "tokenizer"
entropix.tokenizer.tokenizer: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_main.torch_main.class: file
entropix.torch_main.torch_main.label: "torch_main"
entropix.torch_main.torch_main: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_sampler.torch_sampler.class: file
entropix.torch_sampler.torch_sampler.label: "torch_sampler"
entropix.torch_sampler.torch_sampler: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_weights.torch_weights.class: file
entropix.torch_weights.torch_weights.label: "torch_weights"
entropix.torch_weights.torch_weights: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.stats.stats.class: file
entropix.stats.stats.label: "stats"
entropix.stats.stats: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.main.main.class: file
entropix.main.main.label: "main"
entropix.main.main: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.sampler.sampler.class: file
entropix.sampler.sampler.label: "sampler"
entropix.sampler.sampler: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_stats.torch_stats.class: file
entropix.torch_stats.torch_stats.label: "torch_stats"
entropix.torch_stats.torch_stats: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.weights.weights.class: file
entropix.weights.weights.label: "weights"
entropix.weights.weights: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.mcts.mcts.class: file
entropix.mcts.mcts.label: "mcts"
entropix.mcts.mcts: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_model.torch_model.class: file
entropix.torch_model.torch_model.label: "torch_model"
entropix.torch_model.torch_model: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.model.model -> entropix.kvcache.kvcache: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.model.model -> entropix.weights.weights: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.model.model -> entropix.config.config: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.model.model -> entropix.stats.stats: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_main.torch_main -> entropix.torch_model.torch_model: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_main.torch_main -> entropix.tokenizer.tokenizer: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_main.torch_main -> entropix.config.config: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_main.torch_main -> entropix.torch_weights.torch_weights: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_main.torch_main -> entropix.torch_sampler.torch_sampler: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_main.torch_main -> entropix.prompts.prompts: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_main.torch_main -> entropix.torch_kvcache.torch_kvcache: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.main.main -> entropix.weights.weights: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.main.main -> entropix.model.model: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.main.main -> entropix.tokenizer.tokenizer: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.main.main -> entropix.config.config: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.main.main -> entropix.kvcache.kvcache: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.main.main -> entropix.prompts.prompts: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.main.main -> entropix.sampler.sampler: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.mcts.mcts -> entropix.torch_main.torch_main: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_model.torch_model -> entropix.torch_weights.torch_weights: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_model.torch_model -> entropix.torch_stats.torch_stats: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_model.torch_model -> entropix.config.config: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_model.torch_model -> entropix.torch_kvcache.torch_kvcache: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}