vars: {
  d2-config: {
    sketch: true
  }
}
classes: {
  file: {
    label: ""
    shape: diamond
    style: {
      fill: yellow
      shadow: true
    }
  }
}

classes: {
  class: {
    label: ""
    shape: hexagon
    style: {
      fill: lightblue
      shadow: true
    }
  }
}

classes: {
  function: {
    label: ""
    shape: rectangle
    style: {
      fill: white
      shadow: false
    }
  }
}
download_weights.main.class: function
download_weights.main.label: "main"
download_weights.main: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
download_weights.reverse_permute.class: function
download_weights.reverse_permute.label: "reverse_permute"
download_weights.reverse_permute: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
download_weights.translate_key.class: function
download_weights.translate_key.label: "translate_key"
download_weights.translate_key: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
download_weights.fixed_get_imports.class: function
download_weights.fixed_get_imports.label: "fixed_get_imports"
download_weights.fixed_get_imports: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
download_weights.download_weights.class: file
download_weights.download_weights.label: "download_weights"
download_weights.download_weights: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_kvcache.clear.class: function
entropix.torch_kvcache.clear.label: "clear"
entropix.torch_kvcache.clear: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.weights.weights.class: file
entropix.weights.weights.label: "weights"
entropix.weights.weights: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.stats.avg_entropy.class: function
entropix.stats.avg_entropy.label: "avg_entropy"
entropix.stats.avg_entropy: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.weights.LayerWeights.class: class
entropix.weights.LayerWeights.label: "LayerWeights"
entropix.weights.LayerWeights: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.stats.new.class: function
entropix.stats.new.label: "new"
entropix.stats.new: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.config.config.class: file
entropix.config.config.label: "config"
entropix.config.config: {
  style: {
    opacity: 1.00
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.stats.std_error.class: function
entropix.stats.std_error.label: "std_error"
entropix.stats.std_error: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.config.ModelParams.class: class
entropix.config.ModelParams.label: "ModelParams"
entropix.config.ModelParams: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.stats.AttnStats.class: class
entropix.stats.AttnStats.label: "AttnStats"
entropix.stats.AttnStats: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.kvcache.update.class: function
entropix.kvcache.update.label: "update"
entropix.kvcache.update: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.kvcache.kvcache.class: file
entropix.kvcache.kvcache.label: "kvcache"
entropix.kvcache.kvcache: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.weights.load_weights.class: function
entropix.weights.load_weights.label: "load_weights"
entropix.weights.load_weights: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.kvcache.new.class: function
entropix.kvcache.new.label: "new"
entropix.kvcache.new: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.stats.update.class: function
entropix.stats.update.label: "update"
entropix.stats.update: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.weights.XfmrWeights.class: class
entropix.weights.XfmrWeights.label: "XfmrWeights"
entropix.weights.XfmrWeights: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.kvcache.KVCache.class: class
entropix.kvcache.KVCache.label: "KVCache"
entropix.kvcache.KVCache: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.stats.stats.class: file
entropix.stats.stats.label: "stats"
entropix.stats.stats: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_stats.avg_entropy.class: function
entropix.torch_stats.avg_entropy.label: "avg_entropy"
entropix.torch_stats.avg_entropy: {
  style: {
    opacity: 0.44
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_stats.update.class: function
entropix.torch_stats.update.label: "update"
entropix.torch_stats.update: {
  style: {
    opacity: 0.44
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_weights.load_weights.class: function
entropix.torch_weights.load_weights.label: "load_weights"
entropix.torch_weights.load_weights: {
  style: {
    opacity: 0.21
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.prompts.prompts.class: file
entropix.prompts.prompts.label: "prompts"
entropix.prompts.prompts: {
  style: {
    opacity: 0.13
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.prompts.create_prompts_from_csv.class: function
entropix.prompts.create_prompts_from_csv.label: "create_prompts_from_csv"
entropix.prompts.create_prompts_from_csv: {
  style: {
    opacity: 0.12
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_model.feed_forward.class: function
entropix.torch_model.feed_forward.label: "feed_forward"
entropix.torch_model.feed_forward: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_stats.new.class: function
entropix.torch_stats.new.label: "new"
entropix.torch_stats.new: {
  style: {
    opacity: 0.44
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_stats.torch_stats.class: file
entropix.torch_stats.torch_stats.label: "torch_stats"
entropix.torch_stats.torch_stats: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_model.attention.class: function
entropix.torch_model.attention.label: "attention"
entropix.torch_model.attention: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_kvcache.torch_kvcache.class: file
entropix.torch_kvcache.torch_kvcache.label: "torch_kvcache"
entropix.torch_kvcache.torch_kvcache: {
  style: {
    opacity: 0.35
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_stats.AttnStats.class: class
entropix.torch_stats.AttnStats.label: "AttnStats"
entropix.torch_stats.AttnStats: {
  style: {
    opacity: 0.44
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.prompts.create_prompt_template.class: function
entropix.prompts.create_prompt_template.label: "create_prompt_template"
entropix.prompts.create_prompt_template: {
  style: {
    opacity: 0.12
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_weights.torch_weights.class: file
entropix.torch_weights.torch_weights.label: "torch_weights"
entropix.torch_weights.torch_weights: {
  style: {
    opacity: 0.31
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_model.apply_rotary_emb.class: function
entropix.torch_model.apply_rotary_emb.label: "apply_rotary_emb"
entropix.torch_model.apply_rotary_emb: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_model.xfmr.class: function
entropix.torch_model.xfmr.label: "xfmr"
entropix.torch_model.xfmr: {
  style: {
    opacity: 0.83
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_kvcache.KVCache.class: class
entropix.torch_kvcache.KVCache.label: "KVCache"
entropix.torch_kvcache.KVCache: {
  style: {
    opacity: 0.33
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_weights.compare_outputs.class: function
entropix.torch_weights.compare_outputs.label: "compare_outputs"
entropix.torch_weights.compare_outputs: {
  style: {
    opacity: 0.19
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
entropix.torch_weights.load_weights.class: function
entropix.torch_weights.load_weights.label: "load_weights"
entropix.torch_weights.load_weights: {
  style: {
    opacity: 0.12
    stroke: "black"
    stroke-width: 4
    shadow: true
  }
}
download_weights.main -> download_weights.translate_key: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
download_weights.main -> download_weights.fixed_get_imports: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
download_weights.main -> download_weights.reverse_permute: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
download_weights.reverse_permute -> download_weights.translate_key: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
download_weights.translate_key -> download_weights.reverse_permute: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
download_weights.translate_key -> download_weights.fixed_get_imports: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
download_weights.translate_key -> download_weights.main: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
download_weights.translate_key -> download_weights.translate_key: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
download_weights.translate_key -> entropix.torch_kvcache.clear: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
download_weights.fixed_get_imports -> download_weights.translate_key: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
download_weights.fixed_get_imports -> download_weights.fixed_get_imports: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
download_weights.fixed_get_imports -> download_weights.reverse_permute: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
download_weights.download_weights -> entropix.torch_stats.avg_entropy: {
  style.stroke: red
  style.opacity: 0.44
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_stats.update: {
  style.stroke: red
  style.opacity: 0.44
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> download_weights.main: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_weights.load_weights: {
  style.stroke: red
  style.opacity: 0.21
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.config.ModelParams: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.stats.AttnStats: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.kvcache.update: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.prompts.prompts: {
  style.stroke: red
  style.opacity: 0.13
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> download_weights.fixed_get_imports: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.kvcache.kvcache: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.weights.load_weights: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.kvcache.new: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.stats.update: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_model.feed_forward: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.prompts.create_prompts_from_csv: {
  style.stroke: red
  style.opacity: 0.12
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_stats.new: {
  style.stroke: red
  style.opacity: 0.44
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.kvcache.KVCache: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_stats.torch_stats: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.weights.weights: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> download_weights.reverse_permute: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.stats.avg_entropy: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.weights.LayerWeights: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_model.attention: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_kvcache.torch_kvcache: {
  style.stroke: red
  style.opacity: 0.35
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.stats.new: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.config.config: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.stats.std_error: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_kvcache.clear: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_stats.AttnStats: {
  style.stroke: red
  style.opacity: 0.44
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.prompts.create_prompt_template: {
  style.stroke: red
  style.opacity: 0.12
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_weights.load_weights: {
  style.stroke: red
  style.opacity: 0.12
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_weights.torch_weights: {
  style.stroke: red
  style.opacity: 0.31
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_model.apply_rotary_emb: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.weights.XfmrWeights: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_model.xfmr: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> download_weights.translate_key: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.stats.stats: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_kvcache.KVCache: {
  style.stroke: red
  style.opacity: 0.33
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
download_weights.download_weights -> entropix.torch_weights.compare_outputs: {
  style.stroke: red
  style.opacity: 0.19
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_kvcache.clear -> download_weights.reverse_permute: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
entropix.torch_kvcache.clear -> download_weights.translate_key: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
entropix.torch_kvcache.clear -> download_weights.fixed_get_imports: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
entropix.torch_kvcache.clear -> download_weights.main: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
entropix.torch_kvcache.clear -> entropix.config.config: {
  style.stroke: black
  style.opacity: 1.00
  style.stroke-width: 2
}
entropix.weights.weights -> entropix.config.ModelParams: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.weights.weights -> entropix.stats.AttnStats: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.weights.weights -> entropix.weights.LayerWeights: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.weights.weights -> entropix.weights.load_weights: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.weights.weights -> entropix.weights.XfmrWeights: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.weights.weights -> entropix.stats.stats: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.stats.avg_entropy -> entropix.stats.update: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.avg_entropy -> entropix.kvcache.KVCache: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.avg_entropy -> entropix.kvcache.kvcache: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.LayerWeights -> entropix.weights.weights: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.LayerWeights -> entropix.config.ModelParams: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.LayerWeights -> entropix.weights.load_weights: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.new -> entropix.stats.AttnStats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.new -> entropix.stats.avg_entropy: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.new -> entropix.kvcache.kvcache: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.new -> entropix.stats.update: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.new -> entropix.kvcache.KVCache: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.config.config -> entropix.torch_stats.avg_entropy: {
  style.stroke: red
  style.opacity: 0.44
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.torch_stats.update: {
  style.stroke: red
  style.opacity: 0.44
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> download_weights.main: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.config.ModelParams: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.stats.AttnStats: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.prompts.prompts: {
  style.stroke: red
  style.opacity: 0.13
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.kvcache.update: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> download_weights.fixed_get_imports: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.kvcache.kvcache: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.weights.load_weights: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.kvcache.new: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.stats.update: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.prompts.create_prompts_from_csv: {
  style.stroke: red
  style.opacity: 0.12
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.torch_model.feed_forward: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.torch_stats.new: {
  style.stroke: red
  style.opacity: 0.44
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.kvcache.KVCache: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.torch_stats.torch_stats: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.weights.weights: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> download_weights.reverse_permute: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.stats.avg_entropy: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.weights.LayerWeights: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.torch_model.attention: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.torch_kvcache.torch_kvcache: {
  style.stroke: red
  style.opacity: 0.35
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.stats.new: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.torch_weights.load_weights: {
  style.stroke: red
  style.opacity: 0.12
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.torch_kvcache.clear: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.stats.std_error: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.torch_stats.AttnStats: {
  style.stroke: red
  style.opacity: 0.44
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.prompts.create_prompt_template: {
  style.stroke: red
  style.opacity: 0.12
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.torch_weights.torch_weights: {
  style.stroke: red
  style.opacity: 0.31
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.weights.XfmrWeights: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.torch_model.xfmr: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> download_weights.translate_key: {
  style.stroke: red
  style.opacity: 1.00
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.stats.stats: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.torch_kvcache.KVCache: {
  style.stroke: red
  style.opacity: 0.33
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.config.config -> entropix.torch_weights.compare_outputs: {
  style.stroke: red
  style.opacity: 0.19
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.stats.std_error -> entropix.stats.new: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.std_error -> entropix.stats.stats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.std_error -> entropix.stats.AttnStats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.std_error -> entropix.stats.avg_entropy: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.config.ModelParams -> entropix.weights.weights: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.config.ModelParams -> entropix.stats.AttnStats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.config.ModelParams -> entropix.weights.LayerWeights: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.config.ModelParams -> entropix.weights.load_weights: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.config.ModelParams -> entropix.weights.XfmrWeights: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.config.ModelParams -> entropix.stats.stats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.AttnStats -> entropix.weights.weights: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.AttnStats -> entropix.stats.avg_entropy: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.AttnStats -> entropix.weights.LayerWeights: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.AttnStats -> entropix.kvcache.kvcache: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.AttnStats -> entropix.weights.load_weights: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.AttnStats -> entropix.stats.update: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.AttnStats -> entropix.stats.new: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.AttnStats -> entropix.weights.XfmrWeights: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.AttnStats -> entropix.stats.std_error: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.AttnStats -> entropix.kvcache.KVCache: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.AttnStats -> entropix.stats.stats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.update -> entropix.kvcache.update: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.update -> entropix.torch_model.attention: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.update -> entropix.kvcache.new: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.update -> entropix.torch_model.xfmr: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.update -> entropix.torch_model.feed_forward: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.update -> entropix.kvcache.KVCache: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.kvcache -> entropix.stats.avg_entropy: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.kvcache.kvcache -> entropix.kvcache.update: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.kvcache.kvcache -> entropix.torch_model.apply_rotary_emb: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.kvcache.kvcache -> entropix.kvcache.new: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.kvcache.kvcache -> entropix.stats.std_error: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.kvcache.kvcache -> entropix.kvcache.KVCache: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.weights.load_weights -> entropix.weights.XfmrWeights: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.load_weights -> entropix.weights.LayerWeights: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.load_weights -> entropix.stats.stats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.load_weights -> entropix.stats.AttnStats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_stats.torch_stats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_stats.avg_entropy: {
  style.stroke: black
  style.opacity: 0.44
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_weights.torch_weights: {
  style.stroke: black
  style.opacity: 0.31
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.kvcache.update: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_model.apply_rotary_emb: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_model.attention: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_kvcache.torch_kvcache: {
  style.stroke: black
  style.opacity: 0.35
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_weights.compare_outputs: {
  style.stroke: black
  style.opacity: 0.19
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_stats.update: {
  style.stroke: black
  style.opacity: 0.44
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_model.xfmr: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_model.feed_forward: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_weights.load_weights: {
  style.stroke: black
  style.opacity: 0.21
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_stats.AttnStats: {
  style.stroke: black
  style.opacity: 0.44
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_kvcache.KVCache: {
  style.stroke: black
  style.opacity: 0.33
  style.stroke-width: 2
}
entropix.kvcache.new -> entropix.torch_stats.new: {
  style.stroke: black
  style.opacity: 0.44
  style.stroke-width: 2
}
entropix.stats.update -> entropix.kvcache.update: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.update -> entropix.torch_model.apply_rotary_emb: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.update -> entropix.kvcache.kvcache: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.update -> entropix.kvcache.new: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.update -> entropix.stats.new: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.update -> entropix.kvcache.KVCache: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.torch_stats.torch_stats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.weights.weights: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.stats.AttnStats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.stats.avg_entropy: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.kvcache.update: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.torch_model.apply_rotary_emb: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.torch_model.attention: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.kvcache.kvcache: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.kvcache.new: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.stats.update: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.stats.new: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.torch_model.xfmr: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.torch_model.feed_forward: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.stats.std_error: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.kvcache.KVCache: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.weights.XfmrWeights -> entropix.stats.stats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.KVCache -> entropix.stats.avg_entropy: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.KVCache -> entropix.kvcache.update: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.KVCache -> entropix.kvcache.kvcache: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.KVCache -> entropix.kvcache.new: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.KVCache -> entropix.stats.update: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.KVCache -> entropix.stats.new: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.KVCache -> entropix.stats.std_error: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.kvcache.KVCache -> entropix.kvcache.KVCache: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.stats.stats -> entropix.stats.AttnStats: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.stats.stats -> entropix.stats.avg_entropy: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.stats.stats -> entropix.weights.LayerWeights: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.stats.stats -> entropix.weights.load_weights: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.stats.stats -> entropix.stats.update: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.stats.stats -> entropix.stats.new: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.stats.stats -> entropix.stats.std_error: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.avg_entropy -> entropix.torch_stats.new: {
  style.stroke: black
  style.opacity: 0.44
  style.stroke-width: 2
}
entropix.torch_stats.update -> entropix.torch_stats.new: {
  style.stroke: black
  style.opacity: 0.44
  style.stroke-width: 2
}
entropix.torch_stats.update -> entropix.torch_stats.avg_entropy: {
  style.stroke: black
  style.opacity: 0.44
  style.stroke-width: 2
}
entropix.torch_stats.update -> entropix.torch_stats.AttnStats: {
  style.stroke: black
  style.opacity: 0.44
  style.stroke-width: 2
}
entropix.torch_weights.load_weights -> entropix.torch_weights.compare_outputs: {
  style.stroke: black
  style.opacity: 0.19
  style.stroke-width: 2
}
entropix.prompts.prompts -> entropix.prompts.create_prompts_from_csv: {
  style.stroke: red
  style.opacity: 0.12
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.prompts.prompts -> entropix.prompts.create_prompt_template: {
  style.stroke: red
  style.opacity: 0.12
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.prompts.create_prompts_from_csv -> entropix.prompts.create_prompt_template: {
  style.stroke: black
  style.opacity: 0.12
  style.stroke-width: 2
}
entropix.torch_model.feed_forward -> entropix.torch_model.feed_forward: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.torch_model.feed_forward -> entropix.torch_stats.torch_stats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.torch_model.feed_forward -> entropix.torch_model.xfmr: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.torch_stats.new -> entropix.torch_stats.update: {
  style.stroke: black
  style.opacity: 0.44
  style.stroke-width: 2
}
entropix.torch_stats.new -> entropix.torch_kvcache.torch_kvcache: {
  style.stroke: black
  style.opacity: 0.35
  style.stroke-width: 2
}
entropix.torch_stats.torch_stats -> entropix.torch_stats.torch_stats: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.torch_stats.avg_entropy: {
  style.stroke: red
  style.opacity: 0.44
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.torch_weights.torch_weights: {
  style.stroke: red
  style.opacity: 0.31
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.prompts.prompts: {
  style.stroke: red
  style.opacity: 0.13
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.torch_kvcache.KVCache: {
  style.stroke: red
  style.opacity: 0.33
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.torch_kvcache.torch_kvcache: {
  style.stroke: red
  style.opacity: 0.35
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.torch_stats.update: {
  style.stroke: red
  style.opacity: 0.44
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.torch_model.xfmr: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.torch_model.feed_forward: {
  style.stroke: red
  style.opacity: 0.83
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.prompts.create_prompts_from_csv: {
  style.stroke: red
  style.opacity: 0.12
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.torch_stats.new: {
  style.stroke: red
  style.opacity: 0.44
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.torch_weights.load_weights: {
  style.stroke: red
  style.opacity: 0.12
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.torch_stats.AttnStats: {
  style.stroke: red
  style.opacity: 0.44
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.prompts.create_prompt_template: {
  style.stroke: red
  style.opacity: 0.12
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.torch_stats -> entropix.torch_weights.compare_outputs: {
  style.stroke: red
  style.opacity: 0.19
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_model.attention -> entropix.torch_model.apply_rotary_emb: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.torch_model.attention -> entropix.torch_stats.torch_stats: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.torch_model.attention -> entropix.torch_model.xfmr: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.torch_model.attention -> entropix.torch_model.feed_forward: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.torch_kvcache.torch_kvcache -> entropix.torch_kvcache.KVCache: {
  style.stroke: red
  style.opacity: 0.33
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_stats.AttnStats -> entropix.torch_stats.new: {
  style.stroke: black
  style.opacity: 0.44
  style.stroke-width: 2
}
entropix.torch_stats.AttnStats -> entropix.torch_stats.avg_entropy: {
  style.stroke: black
  style.opacity: 0.44
  style.stroke-width: 2
}
entropix.torch_stats.AttnStats -> entropix.torch_stats.update: {
  style.stroke: black
  style.opacity: 0.44
  style.stroke-width: 2
}
entropix.torch_stats.AttnStats -> entropix.torch_kvcache.torch_kvcache: {
  style.stroke: black
  style.opacity: 0.35
  style.stroke-width: 2
}
entropix.prompts.create_prompt_template -> entropix.prompts.create_prompts_from_csv: {
  style.stroke: black
  style.opacity: 0.12
  style.stroke-width: 2
}
entropix.prompts.create_prompt_template -> entropix.torch_weights.load_weights: {
  style.stroke: black
  style.opacity: 0.12
  style.stroke-width: 2
}
entropix.torch_weights.torch_weights -> entropix.prompts.prompts: {
  style.stroke: red
  style.opacity: 0.13
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_weights.torch_weights -> entropix.torch_weights.load_weights: {
  style.stroke: red
  style.opacity: 0.21
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_weights.torch_weights -> entropix.torch_weights.compare_outputs: {
  style.stroke: red
  style.opacity: 0.19
  style.stroke-width: 2
  style.stroke-dash: 5
  style.animated: true
}
entropix.torch_model.apply_rotary_emb -> entropix.kvcache.update: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.torch_model.xfmr -> entropix.torch_model.feed_forward: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.torch_model.xfmr -> entropix.kvcache.update: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.torch_model.xfmr -> entropix.torch_model.attention: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.torch_model.xfmr -> entropix.torch_model.apply_rotary_emb: {
  style.stroke: black
  style.opacity: 0.83
  style.stroke-width: 2
}
entropix.torch_kvcache.KVCache -> entropix.torch_weights.torch_weights: {
  style.stroke: black
  style.opacity: 0.31
  style.stroke-width: 2
}
entropix.torch_kvcache.KVCache -> entropix.torch_weights.compare_outputs: {
  style.stroke: black
  style.opacity: 0.19
  style.stroke-width: 2
}
entropix.torch_weights.compare_outputs -> entropix.prompts.prompts: {
  style.stroke: black
  style.opacity: 0.13
  style.stroke-width: 2
}
entropix.torch_weights.load_weights -> entropix.prompts.create_prompts_from_csv: {
  style.stroke: black
  style.opacity: 0.12
  style.stroke-width: 2
}